FROM python:3.14-alpine

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=python,target=pythonn \
    cp -r pythonn python && pip install . && rm -rf python /build
